Chore/getting started examples
algolia/instantsearch pull request #5591
Opened 2023-04-12 16:21 UTC by dhayab

This PR adds the same "Getting started" example for all flavors of the monorepo. Most of the other examples are more complex, so this should allow people to iterate more easily when contributing on the library.

CodeSandboxes:
- [InstantSearch.js](https://codesandbox.io/s/github/algolia/instantsearch/tree/chore/getting-started-examples/examples/js/getting-started?file=/src/app.js)
- [React InstantSearch](https://codesandbox.io/s/github/algolia/instantsearch/tree/chore/getting-started-examples/examples/react/getting-started)
- [React InstantSearch Hooks](https://codesandbox.io/s/github/algolia/instantsearch/tree/chore/getting-started-examples/examples/react-hooks/getting-started?file=/src/App.tsx)
- [Vue InstantSearch](https://codesandbox.io/s/github/algolia/instantsearch/tree/chore/getting-started-examples/examples/vue/getting-started)

2023-04-13 07:34 UTC, Haroenv commented on examples/vue/getting-started/src/main.js
> +  render: h => h(App),
```suggestion
  render: (h) => h(App),
```

2023-04-18 11:45 UTC, FabienMotte requested changes

2023-04-18 11:45 UTC, FabienMotte commented on examples/js/getting-started/README.md
> +_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch.js/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```suggestion
_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```

2023-04-18 11:45 UTC, FabienMotte commented on examples/react-hooks/getting-started/README.md
> +_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch.js/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```suggestion
_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```

2023-04-18 11:45 UTC, FabienMotte commented on examples/react/getting-started/README.md
> +_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch.js/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```suggestion
_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```

2023-04-18 11:45 UTC, FabienMotte commented on examples/vue/getting-started/README.md
> +_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch.js/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```suggestion
_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
```

2023-04-18 11:45 UTC, FabienMotte commented on examples/js/getting-started/README.md
> +_This project was generated with [create-instantsearch-app](https://github.com/algolia/instantsearch.js/tree/master/packages/create-instantsearch-app) by [Algolia](https://algolia.com)._
I guess we need to update all the README.md from templates in `create-instantsearch-app.
I'll take care of that.

2023-04-18 12:14 UTC, Haroenv approved these changes

2023-04-18 12:26 UTC, merged