chore: release
algolia/instantsearch pull request #5804
Opened 2023-08-08 11:53 UTC by aymeric-giraudet

**Summary**

**Result**

2023-08-08 11:59 UTC, aymeric-giraudet commented on packages/create-instantsearch-app/package.json
> +  "version": "6.5.0",
```suggestion
  "version": "7.0.0",
```

2023-08-08 11:59 UTC, aymeric-giraudet commented on packages/create-instantsearch-app/CHANGELOG.md
> +# [6.5.0](https://github.com/algolia/instantsearch/compare/create-instantsearch-app@6.4.2...create-instantsearch-app@6.5.0) (2023-08-08)
```suggestion
# [7.0.0](https://github.com/algolia/instantsearch/compare/create-instantsearch-app@6.4.2...create-instantsearch-app@7.0.0) (2023-08-08)
```

2023-08-08 11:59 UTC, aymeric-giraudet commented on packages/instantsearch.js/CHANGELOG.md
> +
```suggestion
```

2023-08-08 12:07 UTC, aymeric-giraudet commented on examples/js/calendar-widget/package.json
> +    "instantsearch.js": "4.57.0"
```suggestion
    "instantsearch.js": "4.56.9"
```

2023-08-08 12:08 UTC, aymeric-giraudet commented on examples/js/e-commerce-umd/package.json
> +    "instantsearch.js": "4.57.0"
```suggestion
    "instantsearch.js": "4.56.9"
```

2023-08-08 12:08 UTC, aymeric-giraudet commented on examples/js/e-commerce/package.json
> +    "instantsearch.js": "4.57.0"
```suggestion
    "instantsearch.js": "4.56.9"
```

2023-08-08 12:12 UTC, aymeric-giraudet commented on packages/react-instantsearch-router-nextjs/package.json
> +    "instantsearch.js": "4.57.0",
```suggestion
    "instantsearch.js": "4.56.9",
```

2023-08-08 12:12 UTC, aymeric-giraudet commented on packages/react-instantsearch/package.json
> +    "instantsearch.js": "4.57.0",
```suggestion
    "instantsearch.js": "4.56.9",
```

2023-08-08 12:13 UTC, aymeric-giraudet commented on tests/common/package.json
> +    "instantsearch.js": "4.57.0"
```suggestion
    "instantsearch.js": "4.56.9"
```

2023-08-08 12:13 UTC, aymeric-giraudet commented on tests/mocks/package.json
> +    "instantsearch.js": "4.57.0"
```suggestion
    "instantsearch.js": "4.56.9"
```

2023-08-08 12:13 UTC, aymeric-giraudet commented on tests/utils/package.json
> +    "instantsearch.js": "4.57.0",
```suggestion
    "instantsearch.js": "4.56.9",
```

2023-08-08 13:59 UTC, Haroenv requested changes
let's wait until FX-2554 is done

2023-08-09 08:02 UTC, Haroenv approved these changes

2023-08-09 08:03 UTC, merged