chore: release
algolia/instantsearch pull request #5845
Opened 2023-09-12 14:44 UTC by dhayab

This pull request prepares the following release:
| Repository | Branch | Update |
|---|---|---|
| [instantsearch](https://github.com/algolia/instantsearch) | chore/release-1694529882358 | minor |

### Release Summary
This is going to be published with the following command:

```yarn lerna publish from-package --yes```

### Merging Instructions
When merging this pull request, you need to **Squash and merge** and make sure that the title starts with `chore: release`.
<details>
<summary>See details</summary>

After that, a commit `chore: release` will be added and you or your CI can run `shipjs trigger` to trigger the release based on the commit.
![Squash and merge](https://raw.githubusercontent.com/algolia/shipjs/v0.24.4/assets/squash-and-merge.png)
</details>

---

_This pull request is automatically generated by [Ship.js](https://github.com/algolia/shipjs)_.

2023-09-12 14:51 UTC, dhayab reviewed
There are some whitespace correction due to shipjs working on top of linted files from last PR, and 2 packages have version bumps when they shouldn't (see below).

2023-09-12 14:51 UTC, dhayab commented on packages/instantsearch.css/CHANGELOG.md
This isn't right. I'll fix it manually.

2023-09-12 14:51 UTC, dhayab commented on specs/CHANGELOG.md
This isn't right. I'll fix it manually.

2023-09-13 08:05 UTC, Haroenv approved these changes
lgtm (although possibly a couple internal-only changes trigger a release. Fine for me

2023-09-13 08:05 UTC, Haroenv commented on packages/instantsearch.css/CHANGELOG.md
it seems right now though?

2023-09-13 09:30 UTC, Haroenv requested changes
added the insights PR #5848

2023-09-13 09:38 UTC, dhayab commented on packages/instantsearch.js/CHANGELOG.md
> +**Note:** Version bump only for package instantsearch.js
```suggestion
### Bug Fixes

- **insights**: use init method params type from Search Insights ([#5848](https://github.com/algolia/instantsearch/issues/5848)) ([d05c6c6](https://github.com/algolia/instantsearch/commit/d05c6c69c7662c9551431ae787223029076ff972))
```

2023-09-13 09:50 UTC, Haroenv approved these changes
lgtm (if you don't mind that we'll solve the vue templates later)

2023-09-13 10:01 UTC, merged