feat(recommend): add `useRelatedProducts` Hook
algolia/instantsearch pull request #6159
Opened 2024-04-25 07:51 UTC by sarahdayan

This introduces the `useRelatedProducts` Hook.

https://algolia.atlassian.net/browse/FX-2758

2024-04-25 14:59 UTC, aymeric-giraudet approved these changes

2024-04-25 15:21 UTC, dhayab requested changes

2024-04-25 15:21 UTC, dhayab commented on packages/react-instantsearch-core/src/connectors/useRelatedProducts.ts
The hook should forward a generic type for the shape of the item, similar to what's done in hits. Otherwise end users won't be able to validate their recommendations types.

2024-04-26 12:32 UTC, dhayab approved these changes

2024-04-26 12:50 UTC, merged